# Generated by Django 4.0.4 on 2022-09-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='city_and_state',
        ),
        migrations.AddField(
            model_name='addresses',
            name='city',
            field=models.CharField(default='Lincoln', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='postal_code',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='state',
            field=models.CharField(default='NE', max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City_State',
        ),
    ]
