# Generated by Django 4.0.4 on 2022-09-10 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_remove_addresses_city_and_state_addresses_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_location',
            name='address',
        ),
        migrations.AddField(
            model_name='delivery_location',
            name='city',
            field=models.CharField(default='Lincoln', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_location',
            name='latitude',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_location',
            name='longitude',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_location',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery_location',
            name='postal_code',
            field=models.CharField(default=4, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_location',
            name='state',
            field=models.CharField(default='Ne', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_location',
            name='street',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_location',
            name='suite',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='deliveries.delivery_location'),
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
