# Generated by Django 4.0.4 on 2022-09-10 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_remove_delivery_location_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_location',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
