# Generated by Django 4.0.4 on 2022-09-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_alter_delivery_location_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_location',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='delivery_location',
            unique_together={('name', 'street', 'city', 'state', 'postal_code')},
        ),
    ]
