# Generated by Django 4.0.4 on 2022-09-15 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_alter_delivery_location_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(max_length=200)),
                ('year', models.IntegerField(unique_for_year='year')),
            ],
        ),
        migrations.CreateModel(
            name='ProductChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='fifty_five_delivery',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='lnk_delivery',
        ),
        migrations.DeleteModel(
            name='Delivery_Season',
        ),
        migrations.AddField(
            model_name='editionchoices',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_choice_edition', to='deliveries.productchoices'),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='edition',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='edition_choice', to='deliveries.editionchoices'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveries',
            name='product',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='product_choice', to='deliveries.productchoices'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='editionchoices',
            unique_together={('edition', 'year', 'product')},
        ),
    ]
