# Generated by Django 4.0.4 on 2022-09-16 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_deliveries_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionchoices',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
