# Generated by Django 4.0.4 on 2022-09-18 15:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_delivery_location_hours_delivery_location_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_location',
            name='hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
    ]
